# Generated by Django 4.0.4 on 2022-04-19 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Принято')),
                ('time_in_work', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Готово')),
                ('status', models.CharField(choices=[('o', 'Открыт'), ('g', 'Готов'), ('p', 'Закрыт')], default='o', max_length=1, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('comment', models.CharField(max_length=250, verbose_name='Причина обращения')),
                ('appearance', models.CharField(max_length=100, verbose_name='Внешний вид')),
                ('device', models.CharField(blank=True, choices=[(None, 'Выберите тип устройства'), ('s', 'Смартфон'), ('n', 'Ноутбук'), ('m', 'Мобильный телефон')], max_length=1, verbose_name='Устройство')),
                ('imei_sn', models.CharField(blank=True, max_length=50, verbose_name='Имэй или серийный номер')),
                ('brand', models.CharField(max_length=50, verbose_name='Брэнд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('equipment', models.CharField(max_length=150, verbose_name='Комплектация')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Пароль')),
                ('estimated_price', models.CharField(blank=True, max_length=8, verbose_name='Ориентировочная цена')),
                ('executor', models.ManyToManyField(blank=True, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('manager', models.ManyToManyField(related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'ordering': ['published'],
            },
        ),
    ]
